//! Regression test for `templates/common/ci/local_check.sh.tmpl`'s fmt gate.
//!
//! Empirical bug: `cargo fmt --all -- --check` walks the crate's whole
//! module tree, which includes `src/bindings.rs` — regenerated by every
//! `cargo component build` (wit-bindgen), gitignored, and never emitted in
//! rustfmt's preferred form. A scaffolded extension's own quality gate
//! therefore passed once (the author's code was clean) and then failed
//! forever after — on exactly one file the author never wrote and cannot
//! reformat away: `src/bindings.rs`, regenerated by the gate's own last step
//! (`./build.sh`).
//!
//! This test drives the *actual template content* (`include_str!`, so it
//! tracks the shipped file exactly, not a copy of it) against a minimal,
//! hand-built fixture crate rather than a real `gtdx new` scaffold +
//! `cargo component build`. That needs no cargo-component / wasm toolchain,
//! so it runs in the default `cargo test` rather than gated behind
//! `GTDX_RUN_BUILD=1` like `tests/cli_publish.rs`'s toolchain-dependent
//! tests — the property under test (the fmt step's handling of a
//! misformatted generated file) does not depend on wasm actually building.

use std::path::Path;
use std::process::Command;

const LOCAL_CHECK_SH: &str = include_str!("../templates/common/ci/local_check.sh.tmpl");

/// (Re)write a minimal fixture crate. `bindings_misformatted` /
/// `lib_misformatted` independently control whether `src/bindings.rs` (the
/// generated-file stand-in) and `src/lib.rs` (the author's own code) are
/// each in rustfmt's preferred form.
fn write_fixture(dir: &Path, bindings_misformatted: bool, lib_misformatted: bool) {
    std::fs::create_dir_all(dir.join("src")).unwrap();
    std::fs::create_dir_all(dir.join("ci")).unwrap();

    std::fs::write(
        dir.join("Cargo.toml"),
        "[package]\nname = \"fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n[lib]\npath = \"src/lib.rs\"\n",
    )
    .unwrap();

    let lib_rs = if lib_misformatted {
        "mod bindings;\n\npub fn hello()->&'static str{\"hi\"}\n"
    } else {
        "mod bindings;\n\npub fn hello() -> &'static str {\n    \"hi\"\n}\n"
    };
    std::fs::write(dir.join("src/lib.rs"), lib_rs).unwrap();

    // Stands in for what wit-bindgen actually emits into src/bindings.rs:
    // valid Rust, not in rustfmt's preferred form (mirrors the real diff
    // this bug was found from: a multi-line attribute rustfmt would collapse
    // onto one line).
    let bindings_rs = if bindings_misformatted {
        "#[allow(dead_code)]\npub struct Foo {\n    pub x:   i32,\n}\n"
    } else {
        "#[allow(dead_code)]\npub struct Foo {\n    pub x: i32,\n}\n"
    };
    std::fs::write(dir.join("src/bindings.rs"), bindings_rs).unwrap();

    // A real extension's build.sh runs `cargo component build`, the thing
    // that actually regenerates src/bindings.rs. Standing that toolchain up
    // is a separate, heavier integration concern (see
    // tests/cli_publish.rs's GTDX_RUN_BUILD-gated tests); this test only
    // needs *a* build.sh that exits 0, since what's under test — the fmt
    // gate — runs before it in the script.
    write_executable(
        &dir.join("build.sh"),
        "#!/usr/bin/env bash\necho stub build ok\n",
    );
    write_executable(&dir.join("ci/local_check.sh"), LOCAL_CHECK_SH);
}

fn write_executable(path: &Path, content: &str) {
    std::fs::write(path, content).unwrap();
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o755)).unwrap();
    }
}

fn run_gate(dir: &Path) -> (bool, String, String) {
    let out = Command::new("bash")
        .arg("ci/local_check.sh")
        .current_dir(dir)
        .output()
        .expect("spawn ci/local_check.sh");
    (
        out.status.success(),
        String::from_utf8_lossy(&out.stdout).into_owned(),
        String::from_utf8_lossy(&out.stderr).into_owned(),
    )
}

#[test]
fn gate_ignores_misformatted_generated_bindings_but_still_catches_author_misformatting() {
    let tmp = tempfile::tempdir().unwrap();
    let dir = tmp.path();

    // 1. Author's code is clean; src/bindings.rs looks exactly like a fresh
    //    wit-bindgen regen: not in rustfmt's preferred form. This is the
    //    state right after `./build.sh` on the very first run — the case
    //    that used to fail the gate.
    write_fixture(dir, true, false);
    let (ok, stdout, stderr) = run_gate(dir);
    assert!(
        ok,
        "gate must pass when only the generated src/bindings.rs is out of format\nstdout:\n{stdout}\nstderr:\n{stderr}"
    );

    // 2. Simulate a second build regenerating bindings.rs again (content
    //    changes but remains out of format): "passes twice in a row with a
    //    build in between" must hold.
    write_fixture(dir, true, false);
    let (ok, stdout, stderr) = run_gate(dir);
    assert!(
        ok,
        "gate must still pass on a second run after another 'build'\nstdout:\n{stdout}\nstderr:\n{stderr}"
    );

    // 3. Now the AUTHOR's own file is misformatted (bindings.rs left clean
    //    this time, isolating the assertion to lib.rs) — the gate must fail.
    write_fixture(dir, false, true);
    let (ok, stdout, _stderr) = run_gate(dir);
    assert!(
        !ok,
        "gate must fail when the author's own src/lib.rs is misformatted"
    );
    assert!(
        stdout.contains("lib.rs"),
        "failure output should name the offending file, src/lib.rs:\n{stdout}"
    );

    // 4. Reverting the author's code must make it green again — the failure
    //    in step 3 was real, not a stuck gate.
    write_fixture(dir, false, false);
    let (ok, stdout, stderr) = run_gate(dir);
    assert!(
        ok,
        "gate must pass again once the author's code is reformatted\nstdout:\n{stdout}\nstderr:\n{stderr}"
    );
}

/// A `cargo fmt` failure that reports no file-level diff at all (a parse
/// error, an internal rustfmt panic, ...) must still fail the gate — the
/// filtering must not swallow errors it cannot attribute to a specific file.
#[test]
fn gate_fails_on_a_cargo_fmt_error_that_is_not_a_diff() {
    let tmp = tempfile::tempdir().unwrap();
    let dir = tmp.path();
    write_fixture(dir, false, false);
    // Syntactically invalid Rust: cargo fmt exits non-zero without printing
    // a "Diff in ...:" line for it.
    std::fs::write(
        dir.join("src/lib.rs"),
        "mod bindings;\n\npub fn broken( {\n",
    )
    .unwrap();

    let (ok, _stdout, _stderr) = run_gate(dir);
    assert!(
        !ok,
        "a non-diff cargo fmt failure (e.g. a parse error) must still fail the gate"
    );
}
