//! Conformance checks an addon can run before deploying.
//!
//! The rule in [`assert_apply_consistent`] is the one the platform enforces in
//! production. It lives here so an author runs the same rule rather than a
//! test that resembles it.

use serde_json::Value;

/// One leaf where the applied state disagrees with the plan that was approved.
#[derive(Debug, Clone, PartialEq)]
pub struct Inconsistency {
    /// JSON Pointer to the offending leaf. Empty when the input did not parse.
    pub path: String,
    /// What the plan said.
    pub planned: Value,
    /// What the apply produced. `None` when the key is absent entirely.
    pub observed: Option<Value>,
}

/// Assert that an apply honoured the plan it was given.
///
/// Every leaf in `planned_json` must appear at the same JSON Pointer in
/// `observed_json` with an equal value. Extra keys in the observed state are
/// allowed: an addon may report a server-assigned id or a timestamp it could
/// not have planned.
///
/// Returns every violation rather than the first, because an author fixing
/// them one at a time learns the shape of the problem slowly.
///
/// # Errors
///
/// Returns the list of disagreeing leaves. A single entry with an empty `path`
/// means one of the two inputs did not parse as JSON — reported as a failure
/// rather than a pass, since silently accepting unparseable state is how a
/// check stops checking.
pub fn assert_apply_consistent(
    planned_json: &str,
    observed_json: &str,
) -> Result<(), Vec<Inconsistency>> {
    let planned: Value = serde_json::from_str(planned_json).map_err(|e| {
        vec![Inconsistency {
            path: String::new(),
            planned: Value::String(format!("planned state is not valid JSON: {e}")),
            observed: None,
        }]
    })?;
    let observed: Value = serde_json::from_str(observed_json).map_err(|e| {
        vec![Inconsistency {
            path: String::new(),
            planned: Value::String(format!("observed state is not valid JSON: {e}")),
            observed: None,
        }]
    })?;

    let mut out = Vec::new();
    walk(&planned, Some(&observed), String::new(), &mut out);
    if out.is_empty() { Ok(()) } else { Err(out) }
}

/// Descend `planned`, comparing each leaf against the same position in
/// `observed`. Containers are walked; only leaves are compared, so an object
/// gaining a key is not itself a violation.
fn walk(planned: &Value, observed: Option<&Value>, path: String, out: &mut Vec<Inconsistency>) {
    match planned {
        Value::Object(map) => {
            for (key, child) in map {
                let child_path = format!("{path}/{key}");
                let child_observed = observed.and_then(|o| o.get(key));
                walk(child, child_observed, child_path, out);
            }
        }
        Value::Array(items) => {
            for (i, child) in items.iter().enumerate() {
                let child_path = format!("{path}/{i}");
                let child_observed = observed.and_then(|o| o.get(i));
                walk(child, child_observed, child_path, out);
            }
        }
        leaf => {
            if observed != Some(leaf) {
                out.push(Inconsistency {
                    path,
                    planned: leaf.clone(),
                    observed: observed.cloned(),
                });
            }
        }
    }
}

/// What an addon's `plan` produced, flattened for testing.
///
/// The WIT `plan-outcome` variant lives in the addon's own crate, generated by
/// `cargo component`; this crate cannot name it. An addon adapts its bindgen
/// type into this in one line, and `None` from the closure stands for
/// `deferred`.
#[derive(Debug, Clone, PartialEq)]
pub struct PlanResult {
    pub planned_json: String,
    pub requires_replace: Vec<String>,
}

/// Assert that planning a state against itself is a no-op.
///
/// This is the single most valuable property an addon can be held to. An
/// addon that fails it never converges: every reconcile finds work, the
/// resource never settles, and the symptom — a plan that is never clean —
/// looks like a platform fault rather than an addon defect.
///
/// # Errors
///
/// Returns a human-readable description of the first property violated:
/// a deferred outcome, a non-empty `requires_replace`, or a planned state
/// that differs from the input.
pub fn assert_plan_idempotent(
    current: &str,
    plan: impl Fn(&str, &str) -> Option<PlanResult>,
) -> Result<(), String> {
    let Some(result) = plan(current, current) else {
        return Err(
            "plan(x, x) returned deferred; nothing is missing when current and desired agree"
                .to_string(),
        );
    };

    if !result.requires_replace.is_empty() {
        return Err(format!(
            "plan(x, x) returned requires-replace {:?}; a state that already matches must not be \
             destroyed and recreated",
            result.requires_replace
        ));
    }

    // Both directions, deliberately. `assert_apply_consistent` checks a
    // SUBSET — every leaf of its first argument present in its second — which
    // is right for apply (an addon may report more than it planned) and wrong
    // here. Idempotency needs equality: running it only as
    // `(current, planned)` would pass an addon that ADDS a field on every
    // plan, which is the churning case this property exists to catch.
    let removed = assert_apply_consistent(current, &result.planned_json).err();
    let added = assert_apply_consistent(&result.planned_json, current).err();

    let mut shown: Vec<String> = Vec::new();
    for d in removed.into_iter().flatten() {
        shown.push(format!("{} dropped (planned {})", d.path, d.planned));
    }
    for d in added.into_iter().flatten() {
        shown.push(format!("{} added (plan says {})", d.path, d.planned));
    }

    if shown.is_empty() {
        Ok(())
    } else {
        Err(format!(
            "plan(x, x) did not return x unchanged, so this addon never converges: {}",
            shown.join("; ")
        ))
    }
}

/// Assert that planning the same inputs twice produces the same output.
///
/// A plan that varies cannot be approved: what the user saw in the plan is not
/// what the apply will do.
///
/// # Errors
///
/// Returns a description of how the two calls differed.
pub fn assert_plan_stable(
    current: &str,
    desired: &str,
    plan: impl Fn(&str, &str) -> Option<PlanResult>,
) -> Result<(), String> {
    let first = plan(current, desired);
    let second = plan(current, desired);
    if first == second {
        Ok(())
    } else {
        Err(format!(
            "two identical plan calls differed:\n  first:  {first:?}\n  second: {second:?}"
        ))
    }
}
