//! `Compat` — minimum designer/runner versions plus literal contract version
//! the descriptor was authored against. Parsed eagerly so invalid descriptors
//! fail at deserialize time, not when an installer tries to match.

use semver::{Version, VersionReq};
use serde::{Deserialize, Serialize};

/// Oldest designer whose extension loader understands the `greentic.ai/v2`
/// describe contract — the real floor an extension authored against this SDK
/// requires.
///
/// This is deliberately NOT the SDK/CLI version. The two are different axes:
/// an extension generated by SDK 1.3.x loads on any designer that speaks v2,
/// so pinning `min_designer_version` to the generating SDK would declare a
/// constraint far stricter than the extension actually has.
///
/// Grounded in designer history: designer adopted contract 1.2.x at package
/// version `1.2.3-research`. Anything older (the 1.1.x lineage, contract
/// `0.4.x`) skips a v2 describe at boot.
///
/// **Exception, as of `contributions.views[]` (Phase 1, August 2026) and
/// `contributions.addons[]` (Phase 1, August 2026):** `Contributions` is
/// `#[serde(deny_unknown_fields)]`, so a designer built against a
/// pre-views (respectively pre-addons) contract crate does not ignore a
/// `views` or `addons` key it doesn't recognise — it fails to parse
/// `describe.json` entirely, and the extension does not load. That makes
/// the claim above false for a view-bearing or addon-bearing describe on
/// any designer in the 1.2.0–1.2.9 range: it declares `>=1.2.0` while
/// actually requiring a designer that has both adopted contract 1.2.x *and*
/// learned the field in question, which is a later, currently-unshipped
/// designer release (Phase 4 of the extension-views work; the addon
/// equivalent has no phase number assigned yet). The hazard is doubled for
/// addons versus views: `describe-v2.json`'s `contributions` node is
/// `additionalProperties: false`, so an older consumer rejects an `addons`
/// key at both the schema layer and the serde layer, not just one.
///
/// The top-level `configSchema` (August 2026) joins that same list and does
/// not lengthen it in kind: `DescribeJson` is `#[serde(deny_unknown_fields)]`
/// and `describe-v2.json`'s root is `additionalProperties: false`, so an
/// older consumer rejects a `configSchema`-bearing describe at both layers —
/// the doubled hazard already described for `addons`, arrived at by the same
/// route. It fails closed, which is the wanted behaviour: the extension does
/// not load, rather than loading with the operator's configuration silently
/// dropped and the form never rendered.
///
/// This constant is not raised yet because that floor isn't knowable until
/// a host version ships support for all three fields. Raising it now would
/// also be wrong in a second way: this constant is stamped unconditionally
/// into every describe the SDK scaffolds (`gtdx new`, `gtdx openapi`), not
/// only into describes that use the field, so a raise would gate installs of
/// extensions that carry no `views`, no `addons` and no `configSchema` and
/// are perfectly safe on a 1.2.x designer. **Do not drop this note when one
/// of the three ships and the others have not — raise the constant, and only
/// remove this note, once every describe this SDK can emit (views, addons
/// *and* `configSchema`, together) is safe again at the new floor.**
pub const MIN_DESIGNER_VERSION: &str = "1.2.0";

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct Compat {
    pub min_designer_version: VersionReq,
    pub min_runner_version: VersionReq,
    pub contract_version: Version,
}
