//! `Compat` — minimum designer/runner versions plus literal contract version
//! the descriptor was authored against. Parsed eagerly so invalid descriptors
//! fail at deserialize time, not when an installer tries to match.

use semver::{Version, VersionReq};
use serde::{Deserialize, Serialize};

/// Oldest designer whose extension loader understands the `greentic.ai/v2`
/// describe contract — the real floor an extension authored against this SDK
/// requires.
///
/// This is deliberately NOT the SDK/CLI version. The two are different axes:
/// an extension generated by SDK 1.3.x loads on any designer that speaks v2,
/// so pinning `min_designer_version` to the generating SDK would declare a
/// constraint far stricter than the extension actually has.
///
/// Grounded in designer history: designer adopted contract 1.2.x at package
/// version `1.2.3-research`. Anything older (the 1.1.x lineage, contract
/// `0.4.x`) skips a v2 describe at boot.
pub const MIN_DESIGNER_VERSION: &str = "1.2.0";

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct Compat {
    pub min_designer_version: VersionReq,
    pub min_runner_version: VersionReq,
    pub contract_version: Version,
}
