//! `ConnectorModel` -> generated connector source.
//!
//! Turns the pure [`super::model::ConnectorModel`] Task 1 parses out of an
//! `OpenAPI` spec into the Rust source for a `DesignExtension` connector:
//! `src/tool_meta.rs` (the static `TOOLS` table) and `src/dispatch.rs` (the
//! per-tool HTTP dispatch, mirroring `component-http-ext/src/lib.rs::invoke_tool`).
//!
//! Per-tool codegen (an arbitrary number of tools) is done here in Rust code
//! (string building via `write!`/`push_str`), NOT via the scaffold's `{{key}}`
//! template engine — that engine only substitutes fixed placeholders and
//! cannot express "one array entry per tool".
//!
//! Also provides the small `*_json` helpers `run()` uses to fill the
//! variable-length parts of the `describe.json` shell template
//! (`network`/`secrets`/`contributions.tools`), for the same reason.

use std::fmt::Write as _;

use serde_json::json;

use super::model::{AuthScheme, ConnectorModel, ParamLoc};

/// Generate `src/tool_meta.rs`: a `TOOLS: &[ToolDef]` table, one entry per
/// tool, with the JSON Schema embedded as a raw string literal.
#[must_use]
pub fn gen_tool_meta(model: &ConnectorModel) -> String {
    let mut out = String::new();
    out.push_str(
        "// Generated by `gtdx openapi`. Do not edit by hand — regenerate from the spec.\n\n",
    );
    out.push_str(
        "/// Plain (non-WIT) description of one tool this connector exposes.\n\
         pub struct ToolDef {\n    \
             pub name: &'static str,\n    \
             pub description: &'static str,\n    \
             pub input_schema: &'static str,\n\
         }\n\n",
    );
    out.push_str("pub const TOOLS: &[ToolDef] = &[\n");
    for tool in &model.tools {
        let schema_pretty =
            serde_json::to_string_pretty(&tool.input_schema).unwrap_or_else(|_| "{}".to_string());
        // Raw string literal: schemas are plain JSON and never contain the
        // `"#` delimiter sequence in practice (v1 scope has no free-form
        // string properties containing it); using `r#"..."#` keeps the
        // embedded schema human-readable in the generated source.
        let _ = writeln!(
            out,
            "    ToolDef {{\n        name: {name:?},\n        description: {description:?},\n        input_schema: r#\"{schema_pretty}\"#,\n    }},",
            name = tool.name,
            description = tool.description,
        );
    }
    out.push_str("];\n");
    out
}

/// Generate `src/dispatch.rs`: `pub fn invoke(name, args) -> Result<String,
/// String>` that, for each tool, builds the request URL (base URL + path
/// substitution + query), resolves the auth header via host `secrets::get`,
/// and calls host `http::fetch`. Mirrors `component-http-ext/src/lib.rs::invoke_tool`,
/// generalized to N operations driven by a static per-tool request table.
#[must_use]
pub fn gen_dispatch(model: &ConnectorModel) -> String {
    let mut out = String::new();
    out.push_str(
        "// Generated by `gtdx openapi`. Do not edit by hand — regenerate from the spec.\n\n",
    );
    out.push_str("use crate::bindings::greentic::extension_host::http;\n");
    if model.security.is_some() {
        out.push_str("use crate::bindings::greentic::extension_host::secrets;\n");
    }
    out.push('\n');
    let _ = writeln!(out, "const BASE_URL: &str = {:?};", model.base_url);
    out.push('\n');

    write_requests_table(&mut out, model);
    out.push_str(DISPATCH_HELPERS);
    write_resolve_auth(&mut out, model);
    out
}

/// `struct ToolRequest { .. }` + `const REQUESTS: &[(&str, ToolRequest)]`,
/// one entry per tool.
fn write_requests_table(out: &mut String, model: &ConnectorModel) {
    out.push_str(
        "struct ToolRequest {\n    \
             method: &'static str,\n    \
             path_template: &'static str,\n    \
             path_params: &'static [&'static str],\n    \
             query_params: &'static [&'static str],\n    \
             body_params: &'static [&'static str],\n\
         }\n\n",
    );

    out.push_str("const REQUESTS: &[(&str, ToolRequest)] = &[\n");
    for tool in &model.tools {
        let path_params: Vec<&str> = tool
            .params
            .iter()
            .filter(|p| p.location == ParamLoc::Path)
            .map(|p| p.name.as_str())
            .collect();
        let query_params: Vec<&str> = tool
            .params
            .iter()
            .filter(|p| p.location == ParamLoc::Query)
            .map(|p| p.name.as_str())
            .collect();
        let body_params: Vec<&str> = body_property_names(tool.body.as_ref());
        let _ = writeln!(
            out,
            "    ({name:?}, ToolRequest {{ method: {method:?}, path_template: {path:?}, path_params: &{path_params:?}, query_params: &{query_params:?}, body_params: &{body_params:?} }}),",
            name = tool.name,
            method = tool.method,
            path = tool.path_template,
        );
    }
    out.push_str("];\n");
}

/// `fn resolve_auth() -> Result<Option<(String, String)>, String>`, shaped by
/// the model's (at most one) security scheme.
fn write_resolve_auth(out: &mut String, model: &ConnectorModel) {
    match &model.security {
        None => {
            out.push_str(
                "\nfn resolve_auth() -> Result<Option<(String, String)>, String> {\n    Ok(None)\n}\n",
            );
        }
        Some(AuthScheme::Bearer { secret_ref }) => {
            out.push_str("\nfn resolve_auth() -> Result<Option<(String, String)>, String> {\n");
            let _ = writeln!(out, "    let secret = secrets::get({secret_ref:?})?;");
            out.push_str(
                "    Ok(Some((\"authorization\".to_string(), format!(\"Bearer {secret}\"))))\n}\n",
            );
        }
        Some(AuthScheme::ApiKey {
            header_name,
            secret_ref,
        }) => {
            out.push_str("\nfn resolve_auth() -> Result<Option<(String, String)>, String> {\n");
            let _ = writeln!(out, "    let secret = secrets::get({secret_ref:?})?;");
            let _ = writeln!(out, "    Ok(Some(({header_name:?}.to_string(), secret)))");
            out.push_str("}\n");
        }
    }
}

/// The fixed (model-independent) part of `dispatch.rs`: `invoke` itself plus
/// its small private helpers. Kept as one literal block since it never
/// varies per tool/model — only `REQUESTS` and `resolve_auth` do.
const DISPATCH_HELPERS: &str = r#"
/// Dispatch a tool call by name: build the request from `args` per the
/// matching `ToolRequest` entry, resolve auth, and call the host `http`
/// capability. Returns the response body as a UTF-8 string (lossy).
pub fn invoke(name: &str, args: &serde_json::Value) -> Result<String, String> {
    let (_, req) = REQUESTS
        .iter()
        .find(|entry| entry.0 == name)
        .ok_or_else(|| format!("unknown tool: {name}"))?;

    let mut url = req.path_template.to_string();
    for param in req.path_params {
        let value = args
            .get(*param)
            .ok_or_else(|| format!("missing required path param: {param}"))?;
        url = url.replace(&format!("{{{param}}}"), &json_scalar_to_string(value));
    }
    let mut url = format!("{BASE_URL}{url}");

    let mut query_pairs: Vec<(String, String)> = Vec::new();
    for param in req.query_params {
        if let Some(value) = args.get(*param) {
            query_pairs.push(((*param).to_string(), json_scalar_to_string(value)));
        }
    }
    url = append_query(&url, &query_pairs);

    let mut headers: Vec<(String, String)> = Vec::new();
    if let Some(header) = resolve_auth()? {
        headers.push(header);
    }

    let body = if req.body_params.is_empty() {
        None
    } else {
        let mut map = serde_json::Map::new();
        for param in req.body_params {
            if let Some(value) = args.get(*param) {
                map.insert((*param).to_string(), value.clone());
            }
        }
        Some(serde_json::Value::Object(map).to_string().into_bytes())
    };
    if body.is_some() {
        headers.push(("content-type".to_string(), "application/json".to_string()));
    }

    let request = http::Request {
        method: req.method.to_string(),
        url,
        headers,
        body,
    };
    // Transport / allow-list failures surface as the host `fetch` Err. A
    // non-2xx status is a normal Ok(response) — the caller sees the raw body.
    let response = http::fetch(&request).map_err(|error| format!("http fetch: {error}"))?;
    Ok(String::from_utf8_lossy(&response.body).to_string())
}

fn json_scalar_to_string(value: &serde_json::Value) -> String {
    match value {
        serde_json::Value::String(s) => s.clone(),
        other => other.to_string(),
    }
}

/// Percent-encode per RFC 3986 unreserved set; everything else is `%XX`.
fn percent_encode(input: &str) -> String {
    use std::fmt::Write as _;
    let mut out = String::with_capacity(input.len());
    for byte in input.bytes() {
        match byte {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => {
                out.push(byte as char);
            }
            other => {
                let _ = write!(out, "%{other:02X}");
            }
        }
    }
    out
}

fn append_query(url: &str, pairs: &[(String, String)]) -> String {
    if pairs.is_empty() {
        return url.to_string();
    }
    let joined: Vec<String> = pairs
        .iter()
        .map(|(k, v)| format!("{}={}", percent_encode(k), percent_encode(v)))
        .collect();
    let separator = if url.contains('?') { '&' } else { '?' };
    format!("{url}{separator}{}", joined.join("&"))
}
"#;

/// The top-level object property names of a `requestBody` schema, or empty if
/// there is no body / the body schema isn't an object with `properties`
/// (v1 scope: only flat JSON object bodies are supported).
fn body_property_names(body: Option<&serde_json::Value>) -> Vec<&str> {
    body.and_then(|b| b.get("properties"))
        .and_then(serde_json::Value::as_object)
        .map(|props| props.keys().map(String::as_str).collect())
        .unwrap_or_default()
}

/// `runtime.permissions.network` value for the generated `describe.json`: a
/// single-entry allow-list derived from the connector's base URL.
#[must_use]
pub fn network_allowlist_json(model: &ConnectorModel) -> String {
    let entry = format!("{}/*", model.base_url.trim_end_matches('/'));
    serde_json::to_string(&vec![entry]).unwrap_or_else(|_| "[]".to_string())
}

/// `runtime.permissions.secrets` value for the generated `describe.json`:
/// the connector's single `secret_ref`, or an empty list when the spec had no
/// supported security scheme.
#[must_use]
pub fn secrets_json(model: &ConnectorModel) -> String {
    let list: Vec<&str> = match &model.security {
        Some(AuthScheme::Bearer { secret_ref } | AuthScheme::ApiKey { secret_ref, .. }) => {
            vec![secret_ref.as_str()]
        }
        None => Vec::new(),
    };
    serde_json::to_string(&list).unwrap_or_else(|_| "[]".to_string())
}

/// `contributions.tools` value for the generated `describe.json`: one entry
/// per tool, all pointing at the same `runtime_ref_key` component.
#[must_use]
pub fn tools_contrib_json(model: &ConnectorModel, runtime_ref_key: &str) -> String {
    let entries: Vec<serde_json::Value> = model
        .tools
        .iter()
        .map(|tool| {
            json!({
                "name": tool.name,
                "export": "greentic:extension-design/tools.invoke-tool",
                "runtime_ref": runtime_ref_key,
            })
        })
        .collect();
    serde_json::to_string(&entries).unwrap_or_else(|_| "[]".to_string())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::commands::openapi::model::parse_openapi;

    fn fixture_model() -> ConnectorModel {
        parse_openapi(include_bytes!("fixtures/petstore-min.json"), None, None)
            .expect("fixture parses")
    }

    /// Extract the contents of every `r#"..."#` raw string literal in
    /// generated source, in order of appearance.
    fn extract_raw_string_literals(src: &str) -> Vec<&str> {
        let mut out = Vec::new();
        let mut rest = src;
        while let Some(start) = rest.find("r#\"") {
            let after_open = &rest[start + 3..];
            let Some(end) = after_open.find("\"#") else {
                break;
            };
            out.push(&after_open[..end]);
            rest = &after_open[end + 2..];
        }
        out
    }

    #[test]
    fn gen_tool_meta_declares_the_tools_table() {
        let model = fixture_model();
        let src = gen_tool_meta(&model);
        assert!(src.contains("pub struct ToolDef"));
        assert!(src.contains("pub const TOOLS: &[ToolDef] = &["));
        assert!(src.contains("name: \"getPetById\""));
        assert!(src.contains("name: \"createPet\""));
    }

    #[test]
    fn gen_tool_meta_input_schemas_are_all_valid_json() {
        let model = fixture_model();
        let src = gen_tool_meta(&model);
        let literals = extract_raw_string_literals(&src);
        assert_eq!(
            literals.len(),
            model.tools.len(),
            "expected one raw-string schema literal per tool"
        );
        for literal in literals {
            let parsed: serde_json::Value =
                serde_json::from_str(literal).expect("embedded input_schema is valid JSON");
            assert_eq!(parsed["type"], "object");
        }
    }

    #[test]
    fn gen_dispatch_declares_invoke_and_per_tool_requests() {
        let model = fixture_model();
        let src = gen_dispatch(&model);
        assert!(src.contains("pub fn invoke(name: &str, args: &serde_json::Value)"));
        assert!(src.contains("\"getPetById\""));
        assert!(src.contains("\"createPet\""));
        assert!(src.contains("path_template: \"/pets/{id}\""));
        assert!(src.contains("method: \"GET\""));
        assert!(src.contains("method: \"POST\""));
        assert!(src.contains("path_params: &[\"id\"]"));
        assert!(src.contains("query_params: &[\"verbose\"]"));
        assert!(src.contains("body_params: &[\"name\", \"tag\"]"));
    }

    #[test]
    fn gen_dispatch_resolves_bearer_auth_from_the_model_security() {
        let model = fixture_model();
        let src = gen_dispatch(&model);
        assert!(src.contains("use crate::bindings::greentic::extension_host::secrets;"));
        assert!(src.contains("secrets::get(\"secret://petstore-mini/bearerAuth\")"));
        assert!(src.contains("format!(\"Bearer {secret}\")"));
    }

    #[test]
    fn gen_dispatch_without_security_skips_the_secrets_import_and_returns_no_auth() {
        let mut model = fixture_model();
        model.security = None;
        let src = gen_dispatch(&model);
        assert!(!src.contains("extension_host::secrets"));
        assert!(src.contains(
            "fn resolve_auth() -> Result<Option<(String, String)>, String> {\n    Ok(None)\n}"
        ));
    }

    #[test]
    fn network_allowlist_json_wildcards_the_base_url() {
        let model = fixture_model();
        let json = network_allowlist_json(&model);
        let parsed: serde_json::Value = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, json!(["https://api.example.com/v1/*"]));
    }

    #[test]
    fn secrets_json_lists_the_bearer_secret_ref() {
        let model = fixture_model();
        let json = secrets_json(&model);
        let parsed: serde_json::Value = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, json!(["secret://petstore-mini/bearerAuth"]));
    }

    #[test]
    fn secrets_json_is_empty_without_a_security_scheme() {
        let mut model = fixture_model();
        model.security = None;
        let json = secrets_json(&model);
        let parsed: serde_json::Value = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, json!([]));
    }

    #[test]
    fn tools_contrib_json_has_one_entry_per_tool() {
        let model = fixture_model();
        let json = tools_contrib_json(&model, "petstore-mini");
        let parsed: serde_json::Value = serde_json::from_str(&json).unwrap();
        let arr = parsed.as_array().unwrap();
        assert_eq!(arr.len(), model.tools.len());
        assert!(arr.iter().any(|entry| entry["name"] == "getPetById"));
        assert!(
            arr.iter()
                .all(|entry| entry["runtime_ref"] == "petstore-mini")
        );
    }
}
