//! `ConnectorModel` -> generated connector source.
//!
//! Turns the pure [`super::model::ConnectorModel`] Task 1 parses out of an
//! `OpenAPI` spec into the Rust source for a `DesignExtension` connector:
//! `src/tool_meta.rs` (the static `TOOLS` table) and `src/dispatch.rs` (the
//! per-tool HTTP dispatch, mirroring `component-http-ext/src/lib.rs::invoke_tool`).
//!
//! Per-tool codegen (an arbitrary number of tools) is done here in Rust code
//! (string building via `write!`/`push_str`), NOT via the scaffold's `{{key}}`
//! template engine — that engine only substitutes fixed placeholders and
//! cannot express "one array entry per tool".
//!
//! Also provides the small `*_json` helpers `run()` uses to fill the
//! variable-length parts of the `describe.json` shell template
//! (`network`/`secrets`/`contributions.tools`), for the same reason.

use std::fmt::Write as _;

use serde_json::json;

use super::model::{AuthScheme, ConnectorModel, ParamLoc};

/// Generate `src/tool_meta.rs`: a `TOOLS: &[ToolDef]` table, one entry per
/// tool, with the JSON Schema embedded as a Debug-escaped string literal.
#[must_use]
pub fn gen_tool_meta(model: &ConnectorModel) -> String {
    let mut out = String::new();
    out.push_str(
        "// Generated by `gtdx openapi`. Do not edit by hand — regenerate from the spec.\n\n",
    );
    out.push_str(
        "/// Plain (non-WIT) description of one tool this connector exposes.\n\
         pub struct ToolDef {\n    \
             pub name: &'static str,\n    \
             pub description: &'static str,\n    \
             pub input_schema: &'static str,\n\
         }\n\n",
    );
    out.push_str("pub const TOOLS: &[ToolDef] = &[\n");
    for tool in &model.tools {
        let schema_pretty =
            serde_json::to_string_pretty(&tool.input_schema).unwrap_or_else(|_| "{}".to_string());
        // Emitted as a normal Debug-escaped string literal (like `name` and
        // `description` above), NOT a raw string (`r#"..."#`). Spec
        // descriptions are free-form text pulled straight from real-world
        // `OpenAPI` documents (Stripe/Shopify, etc.) and routinely contain a
        // `"` immediately followed by a `#` — e.g. a description quoting a
        // hashtag — which would prematurely close a `r#"..."#` literal and
        // produce a generated crate that fails to compile. `{:?}` escapes
        // quotes/backslashes/control characters, so it's always valid
        // regardless of what the schema text contains.
        let _ = writeln!(
            out,
            "    ToolDef {{\n        name: {name:?},\n        description: {description:?},\n        input_schema: {schema_pretty:?},\n    }},",
            name = tool.name,
            description = tool.description,
        );
    }
    out.push_str("];\n");
    out
}

/// Generate `src/dispatch.rs`: `pub fn invoke(name, args) -> Result<String,
/// String>` that, for each tool, builds the request URL (base URL + path
/// substitution + query), resolves the auth header via host `secrets::get`,
/// and calls host `http::fetch`. Mirrors `component-http-ext/src/lib.rs::invoke_tool`,
/// generalized to N operations driven by a static per-tool request table.
#[must_use]
pub fn gen_dispatch(model: &ConnectorModel) -> String {
    let mut out = String::new();
    out.push_str(
        "// Generated by `gtdx openapi`. Do not edit by hand — regenerate from the spec.\n\n",
    );
    out.push_str("use crate::bindings::greentic::extension_host::http;\n");
    if model.security.is_some() {
        out.push_str("use crate::bindings::greentic::extension_host::secrets;\n");
    }
    out.push('\n');
    // Trimmed the same way `network_allowlist_json` trims the base URL used
    // for the allow-list entry, so `https://api.example.com/` + `/pets`
    // produces `.../pets`, not `.../<empty>/pets`.
    let _ = writeln!(
        out,
        "const BASE_URL: &str = {:?};",
        model.base_url.trim_end_matches('/')
    );
    out.push('\n');

    write_requests_table(&mut out, model);
    out.push_str(DISPATCH_HELPERS);
    write_resolve_auth(&mut out, model);
    out
}

/// `struct ToolRequest { .. }` + `const REQUESTS: &[(&str, ToolRequest)]`,
/// one entry per tool.
fn write_requests_table(out: &mut String, model: &ConnectorModel) {
    out.push_str(
        "struct ToolRequest {\n    \
             method: &'static str,\n    \
             path_template: &'static str,\n    \
             path_params: &'static [&'static str],\n    \
             query_params: &'static [&'static str],\n    \
             body_params: &'static [&'static str],\n\
         }\n\n",
    );

    out.push_str("const REQUESTS: &[(&str, ToolRequest)] = &[\n");
    for tool in &model.tools {
        let path_params: Vec<&str> = tool
            .params
            .iter()
            .filter(|p| p.location == ParamLoc::Path)
            .map(|p| p.name.as_str())
            .collect();
        let query_params: Vec<&str> = tool
            .params
            .iter()
            .filter(|p| p.location == ParamLoc::Query)
            .map(|p| p.name.as_str())
            .collect();
        let body_params: Vec<&str> = body_property_names(tool.body.as_ref());
        let _ = writeln!(
            out,
            "    ({name:?}, ToolRequest {{ method: {method:?}, path_template: {path:?}, path_params: &{path_params:?}, query_params: &{query_params:?}, body_params: &{body_params:?} }}),",
            name = tool.name,
            method = tool.method,
            path = tool.path_template,
        );
    }
    out.push_str("];\n");
}

/// `fn resolve_auth() -> Result<Option<(String, String)>, String>`, shaped by
/// the model's (at most one) security scheme.
fn write_resolve_auth(out: &mut String, model: &ConnectorModel) {
    match &model.security {
        None => {
            out.push_str(
                "\nfn resolve_auth() -> Result<Option<(String, String)>, String> {\n    Ok(None)\n}\n",
            );
        }
        Some(AuthScheme::Bearer { secret_ref }) => {
            out.push_str("\nfn resolve_auth() -> Result<Option<(String, String)>, String> {\n");
            let _ = writeln!(out, "    let secret = secrets::get({secret_ref:?})?;");
            out.push_str(
                "    Ok(Some((\"authorization\".to_string(), format!(\"Bearer {secret}\"))))\n}\n",
            );
        }
        Some(AuthScheme::ApiKey {
            header_name,
            secret_ref,
        }) => {
            out.push_str("\nfn resolve_auth() -> Result<Option<(String, String)>, String> {\n");
            let _ = writeln!(out, "    let secret = secrets::get({secret_ref:?})?;");
            let _ = writeln!(out, "    Ok(Some(({header_name:?}.to_string(), secret)))");
            out.push_str("}\n");
        }
    }
}

/// The fixed (model-independent) part of `dispatch.rs`: `invoke` itself plus
/// its small private helpers. Kept as one literal block since it never
/// varies per tool/model — only `REQUESTS` and `resolve_auth` do.
const DISPATCH_HELPERS: &str = r#"
/// Dispatch a tool call by name: build the request from `args` per the
/// matching `ToolRequest` entry, resolve auth, and call the host `http`
/// capability. Returns a JSON envelope string `{"status", "ok", "body"}` —
/// mirrors `component-http-ext/src/output.rs::map_response` — so the caller
/// can distinguish a 4xx/5xx response from a 2xx one; only transport /
/// allow-list failures surface as `Err`.
pub fn invoke(name: &str, args: &serde_json::Value) -> Result<String, String> {
    let (_, req) = REQUESTS
        .iter()
        .find(|entry| entry.0 == name)
        .ok_or_else(|| format!("unknown tool: {name}"))?;

    let mut url = req.path_template.to_string();
    for param in req.path_params {
        let value = args
            .get(*param)
            .ok_or_else(|| format!("missing required path param: {param}"))?;
        url = url.replace(
            &format!("{{{param}}}"),
            &percent_encode(&json_scalar_to_string(value)),
        );
    }
    let mut url = format!("{BASE_URL}{url}");

    let mut query_pairs: Vec<(String, String)> = Vec::new();
    for param in req.query_params {
        if let Some(value) = args.get(*param) {
            query_pairs.push(((*param).to_string(), json_scalar_to_string(value)));
        }
    }
    url = append_query(&url, &query_pairs);

    let mut headers: Vec<(String, String)> = Vec::new();
    if let Some(header) = resolve_auth()? {
        headers.push(header);
    }

    let body = if req.body_params.is_empty() {
        None
    } else {
        let mut map = serde_json::Map::new();
        for param in req.body_params {
            if let Some(value) = args.get(*param) {
                map.insert((*param).to_string(), value.clone());
            }
        }
        Some(serde_json::Value::Object(map).to_string().into_bytes())
    };
    if body.is_some() {
        headers.push(("content-type".to_string(), "application/json".to_string()));
    }

    let request = http::Request {
        method: req.method.to_string(),
        url,
        headers,
        body,
    };
    // Transport / allow-list failures surface as the host `fetch` Err. A
    // non-2xx status is NOT an error — it is folded into the returned
    // envelope's `status`/`ok` fields so the caller (an LLM tool-call site)
    // can tell a 404 apart from a 200 without inspecting exception text.
    let response = http::fetch(&request).map_err(|error| format!("http fetch: {error}"))?;
    Ok(map_response(response.status, &response.headers, &response.body).to_string())
}

/// Map a host HTTP response into the `{"status", "ok", "body"}` envelope
/// returned by `invoke`. The body is parsed as JSON when the `content-type`
/// header indicates JSON and parsing succeeds; otherwise it is returned as a
/// UTF-8 string value. Mirrors `component-http-ext/src/output.rs::map_response`.
fn map_response(status: u16, headers: &[(String, String)], body: &[u8]) -> serde_json::Value {
    let is_json = headers.iter().any(|(key, value)| {
        key.eq_ignore_ascii_case("content-type") && value.to_ascii_lowercase().contains("json")
    });
    let body_value = if is_json {
        serde_json::from_slice::<serde_json::Value>(body)
            .unwrap_or_else(|_| serde_json::Value::String(String::from_utf8_lossy(body).into_owned()))
    } else {
        serde_json::Value::String(String::from_utf8_lossy(body).into_owned())
    };
    serde_json::json!({
        "status": status,
        "ok": (200..300).contains(&status),
        "body": body_value,
    })
}

fn json_scalar_to_string(value: &serde_json::Value) -> String {
    match value {
        serde_json::Value::String(s) => s.clone(),
        other => other.to_string(),
    }
}

/// Percent-encode per RFC 3986 unreserved set; everything else is `%XX`.
fn percent_encode(input: &str) -> String {
    use std::fmt::Write as _;
    let mut out = String::with_capacity(input.len());
    for byte in input.bytes() {
        match byte {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => {
                out.push(byte as char);
            }
            other => {
                let _ = write!(out, "%{other:02X}");
            }
        }
    }
    out
}

fn append_query(url: &str, pairs: &[(String, String)]) -> String {
    if pairs.is_empty() {
        return url.to_string();
    }
    let joined: Vec<String> = pairs
        .iter()
        .map(|(k, v)| format!("{}={}", percent_encode(k), percent_encode(v)))
        .collect();
    let separator = if url.contains('?') { '&' } else { '?' };
    format!("{url}{separator}{}", joined.join("&"))
}
"#;

/// The top-level object property names of a `requestBody` schema, or empty if
/// there is no body / the body schema isn't an object with `properties`
/// (v1 scope: only flat JSON object bodies are supported).
fn body_property_names(body: Option<&serde_json::Value>) -> Vec<&str> {
    body.and_then(|b| b.get("properties"))
        .and_then(serde_json::Value::as_object)
        .map(|props| props.keys().map(String::as_str).collect())
        .unwrap_or_default()
}

/// `runtime.permissions.network` value for the generated `describe.json`: a
/// single-entry allow-list derived from the connector's base URL.
#[must_use]
pub fn network_allowlist_json(model: &ConnectorModel) -> String {
    let entry = format!("{}/*", model.base_url.trim_end_matches('/'));
    serde_json::to_string(&vec![entry]).unwrap_or_else(|_| "[]".to_string())
}

/// `runtime.permissions.secrets` value for the generated `describe.json`:
/// the connector's single `secret_ref`, or an empty list when the spec had no
/// supported security scheme.
#[must_use]
pub fn secrets_json(model: &ConnectorModel) -> String {
    let list: Vec<&str> = match &model.security {
        Some(AuthScheme::Bearer { secret_ref } | AuthScheme::ApiKey { secret_ref, .. }) => {
            vec![secret_ref.as_str()]
        }
        None => Vec::new(),
    };
    serde_json::to_string(&list).unwrap_or_else(|_| "[]".to_string())
}

/// `contributions.tools` value for the generated `describe.json`: one entry
/// per tool, all pointing at the same `runtime_ref_key` component.
#[must_use]
pub fn tools_contrib_json(model: &ConnectorModel, runtime_ref_key: &str) -> String {
    let entries: Vec<serde_json::Value> = model
        .tools
        .iter()
        .map(|tool| {
            json!({
                "name": tool.name,
                "export": "greentic:extension-design/tools.invoke-tool",
                "runtime_ref": runtime_ref_key,
            })
        })
        .collect();
    serde_json::to_string(&entries).unwrap_or_else(|_| "[]".to_string())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::commands::openapi::model::parse_openapi;

    fn fixture_model() -> ConnectorModel {
        parse_openapi(include_bytes!("fixtures/petstore-min.json"), None, None)
            .expect("fixture parses")
    }

    /// Extract the still-escaped contents of every `input_schema: "..."`
    /// Debug string literal in generated `tool_meta.rs` source, in order of
    /// appearance. Byte-wise scanning is safe here: it only ever compares
    /// against the ASCII `\` and `"` bytes, and any multi-byte UTF-8
    /// character has every byte >= 0x80, so it can never be mistaken for
    /// either — the slice boundaries this returns always land on a byte that
    /// was matched literally, which is always a valid char boundary.
    fn extract_input_schema_literals(src: &str) -> Vec<String> {
        const MARKER: &str = "input_schema: \"";
        let mut out = Vec::new();
        let mut rest = src;
        while let Some(start) = rest.find(MARKER) {
            let after_open = &rest[start + MARKER.len()..];
            let bytes = after_open.as_bytes();
            let mut i = 0usize;
            let mut end = None;
            while i < bytes.len() {
                match bytes[i] {
                    b'\\' => i += 2,
                    b'"' => {
                        end = Some(i);
                        break;
                    }
                    _ => i += 1,
                }
            }
            let Some(end) = end else { break };
            out.push(after_open[..end].to_string());
            rest = &after_open[end + 1..];
        }
        out
    }

    /// Reverse a Rust `Debug`-formatted (`{:?}`) string literal's contents
    /// back to the original text, e.g. `she said \"#winning\"` -> `she said
    /// "#winning"`. Only used in tests, to prove the embedded schema
    /// round-trips through the generated source.
    fn unescape_debug_string(escaped: &str) -> String {
        let mut out = String::with_capacity(escaped.len());
        let mut chars = escaped.chars();
        while let Some(ch) = chars.next() {
            if ch != '\\' {
                out.push(ch);
                continue;
            }
            match chars.next() {
                Some('"') => out.push('"'),
                Some('\\') => out.push('\\'),
                Some('n') => out.push('\n'),
                Some('t') => out.push('\t'),
                Some('r') => out.push('\r'),
                Some('0') => out.push('\0'),
                Some('u') if chars.next() == Some('{') => {
                    let hex: String = chars.by_ref().take_while(|c| *c != '}').collect();
                    if let Ok(code) = u32::from_str_radix(&hex, 16)
                        && let Some(decoded) = char::from_u32(code)
                    {
                        out.push(decoded);
                    }
                }
                Some(other) => out.push(other),
                None => {}
            }
        }
        out
    }

    #[test]
    fn gen_tool_meta_declares_the_tools_table() {
        let model = fixture_model();
        let src = gen_tool_meta(&model);
        assert!(src.contains("pub struct ToolDef"));
        assert!(src.contains("pub const TOOLS: &[ToolDef] = &["));
        assert!(src.contains("name: \"getPetById\""));
        assert!(src.contains("name: \"createPet\""));
    }

    #[test]
    fn gen_tool_meta_input_schemas_are_all_valid_json() {
        let model = fixture_model();
        let src = gen_tool_meta(&model);
        assert!(
            !src.contains("r#\""),
            "input_schema must never be emitted as a raw string literal"
        );
        let literals = extract_input_schema_literals(&src);
        assert_eq!(
            literals.len(),
            model.tools.len(),
            "expected one input_schema string literal per tool"
        );
        for literal in literals {
            let unescaped = unescape_debug_string(&literal);
            let parsed: serde_json::Value =
                serde_json::from_str(&unescaped).expect("embedded input_schema is valid JSON");
            assert_eq!(parsed["type"], "object");
        }
    }

    /// FIX 1 regression test: a real-world spec description containing a
    /// literal `"` immediately followed by `#` (e.g. quoting a hashtag) used
    /// to prematurely terminate the `r#"..."#` raw string that embedded the
    /// schema, producing a generated crate that fails to compile. The
    /// `petstore-min.json` fixture's `createPet.name` property description
    /// is exactly this case: `the pet's name, e.g. she said "#winning" once`.
    #[test]
    fn gen_tool_meta_survives_a_quote_hash_sequence_in_a_schema_description() {
        let model = fixture_model();
        let src = gen_tool_meta(&model);

        // (a) no raw-string opener for the schema anywhere in the output.
        assert!(!src.contains("input_schema: r#"));

        // (b) the embedded schema, once unescaped, is valid JSON and the
        // description round-trips byte-for-byte through the generated
        // source.
        let literals = extract_input_schema_literals(&src);
        let create_pet_index = model
            .tools
            .iter()
            .position(|tool| tool.name == "createPet")
            .expect("fixture has a createPet tool");
        let create_pet_literal = literals
            .get(create_pet_index)
            .expect("one input_schema literal per tool, in model.tools order");
        let unescaped = unescape_debug_string(create_pet_literal);
        let parsed: serde_json::Value =
            serde_json::from_str(&unescaped).expect("embedded input_schema is valid JSON");
        assert_eq!(
            parsed["properties"]["name"]["description"],
            serde_json::json!("the pet's name, e.g. she said \"#winning\" once")
        );
    }

    #[test]
    fn gen_dispatch_declares_invoke_and_per_tool_requests() {
        let model = fixture_model();
        let src = gen_dispatch(&model);
        assert!(src.contains("pub fn invoke(name: &str, args: &serde_json::Value)"));
        assert!(src.contains("\"getPetById\""));
        assert!(src.contains("\"createPet\""));
        assert!(src.contains("path_template: \"/pets/{id}\""));
        assert!(src.contains("method: \"GET\""));
        assert!(src.contains("method: \"POST\""));
        assert!(src.contains("path_params: &[\"id\"]"));
        assert!(src.contains("query_params: &[\"verbose\"]"));
        assert!(src.contains("body_params: &[\"name\", \"tag\"]"));
    }

    #[test]
    fn gen_dispatch_resolves_bearer_auth_from_the_model_security() {
        let model = fixture_model();
        let src = gen_dispatch(&model);
        assert!(src.contains("use crate::bindings::greentic::extension_host::secrets;"));
        assert!(src.contains("secrets::get(\"secret://petstore-mini/bearerAuth\")"));
        assert!(src.contains("format!(\"Bearer {secret}\")"));
    }

    #[test]
    fn gen_dispatch_without_security_skips_the_secrets_import_and_returns_no_auth() {
        let mut model = fixture_model();
        model.security = None;
        let src = gen_dispatch(&model);
        assert!(!src.contains("extension_host::secrets"));
        assert!(src.contains(
            "fn resolve_auth() -> Result<Option<(String, String)>, String> {\n    Ok(None)\n}"
        ));
    }

    /// FIX 2 regression test: `invoke` must return a structured envelope
    /// (mirrors `component-http-ext/src/output.rs::map_response`) instead of
    /// silently discarding the HTTP status, so a 4xx/5xx doesn't look
    /// identical to a 2xx to the caller.
    #[test]
    fn gen_dispatch_invoke_returns_a_status_envelope_not_the_raw_body() {
        let model = fixture_model();
        let src = gen_dispatch(&model);
        assert!(
            !src.contains("Ok(String::from_utf8_lossy(&response.body).to_string())"),
            "invoke must not return the raw body directly — the HTTP status would be lost"
        );
        assert!(src.contains("fn map_response("));
        assert!(src.contains("\"status\": status"));
        assert!(src.contains("\"ok\": (200..300).contains(&status)"));
        assert!(src.contains("\"body\": body_value"));
        assert!(src.contains(
            "Ok(map_response(response.status, &response.headers, &response.body).to_string())"
        ));
    }

    /// FIX 3a regression test: path parameter values must be percent-encoded
    /// the same way query parameter values already are, so a value with
    /// reserved characters (e.g. `/` or a space) doesn't produce a malformed
    /// URL.
    #[test]
    fn gen_dispatch_percent_encodes_path_params() {
        let model = fixture_model();
        let src = gen_dispatch(&model);
        assert!(
            src.contains("&percent_encode(&json_scalar_to_string(value))"),
            "path param substitution must reuse the same percent_encode helper as query params"
        );
    }

    /// FIX 3b regression test: a `base_url` with a trailing slash must not
    /// produce a double slash when joined with a path template that starts
    /// with `/`.
    #[test]
    fn gen_dispatch_trims_a_trailing_slash_from_base_url() {
        let mut model = fixture_model();
        model.base_url = "https://api.example.com/v1/".to_string();
        let src = gen_dispatch(&model);
        assert!(src.contains("const BASE_URL: &str = \"https://api.example.com/v1\";"));
        assert!(!src.contains("https://api.example.com/v1/\""));
    }

    #[test]
    fn network_allowlist_json_wildcards_the_base_url() {
        let model = fixture_model();
        let json = network_allowlist_json(&model);
        let parsed: serde_json::Value = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, json!(["https://api.example.com/v1/*"]));
    }

    #[test]
    fn secrets_json_lists_the_bearer_secret_ref() {
        let model = fixture_model();
        let json = secrets_json(&model);
        let parsed: serde_json::Value = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, json!(["secret://petstore-mini/bearerAuth"]));
    }

    #[test]
    fn secrets_json_is_empty_without_a_security_scheme() {
        let mut model = fixture_model();
        model.security = None;
        let json = secrets_json(&model);
        let parsed: serde_json::Value = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, json!([]));
    }

    #[test]
    fn tools_contrib_json_has_one_entry_per_tool() {
        let model = fixture_model();
        let json = tools_contrib_json(&model, "petstore-mini");
        let parsed: serde_json::Value = serde_json::from_str(&json).unwrap();
        let arr = parsed.as_array().unwrap();
        assert_eq!(arr.len(), model.tools.len());
        assert!(arr.iter().any(|entry| entry["name"] == "getPetById"));
        assert!(
            arr.iter()
                .all(|entry| entry["runtime_ref"] == "petstore-mini")
        );
    }
}
