//! `gtdx openapi` — generate a `DesignExtension` connector from an `OpenAPI`
//! 3.0 spec.
//!
//! Pipeline: read the spec -> [`model::parse_openapi`] -> render the static
//! "shell" templates (`Cargo.toml`, `describe.json`, `wit/world.wit`,
//! `src/lib.rs`, `rust-toolchain.toml`, `build.sh`) via the scaffold's
//! `{{key}}` engine -> generate the per-tool sources (`src/tool_meta.rs`,
//! `src/dispatch.rs`) in code via [`codegen`] -> write the WIT contract deps +
//! `.gtdx-contract.lock` via [`crate::commands::new::write_wit_and_lock`].

pub mod codegen;
pub mod model;

use std::{
    fs,
    path::{Path, PathBuf},
};

use anyhow::Context as _;
use clap::Args as ClapArgs;

use crate::commands::new::write_wit_and_lock;
use crate::scaffold::embedded;
use crate::scaffold::template::{self, Context};
use codegen::{
    gen_dispatch, gen_tool_meta, network_allowlist_json, secrets_json, tools_contrib_json,
};
use model::{ConnectorModel, parse_openapi, slugify};

#[derive(ClapArgs, Debug)]
pub struct Args {
    /// Path to the `OpenAPI` 3.0 spec (JSON or YAML).
    pub spec: PathBuf,

    /// Connector name override (defaults to the spec's `info.title`).
    #[arg(short = 'n', long)]
    pub name: Option<String>,

    /// Output directory (defaults to `./<slugified-name>`).
    #[arg(short = 'o', long)]
    pub out: Option<PathBuf>,

    /// Base URL override (defaults to the spec's first `servers[]` entry).
    #[arg(long = "base-url")]
    pub base_url: Option<String>,
}

/// Generate a `DesignExtension` connector project from `args.spec` into
/// `args.out` (or `./<slug>`).
pub fn run(args: &Args) -> anyhow::Result<()> {
    let spec_bytes = fs::read(&args.spec)
        .with_context(|| format!("failed to read OpenAPI spec at {}", args.spec.display()))?;
    let model = parse_openapi(&spec_bytes, args.name.as_deref(), args.base_url.as_deref())?;

    if model.tools.is_empty() {
        eprintln!(
            "warning: no tools were generated from this spec — see the warnings above for why each operation was skipped"
        );
    }

    let slug = slugify(&model.name);
    let target = args.out.clone().unwrap_or_else(|| PathBuf::from(&slug));
    fs::create_dir_all(&target)?;

    let ctx = build_context(&model, &slug);

    let mut files_written = render_static_templates(&ctx, &target)?;
    files_written += write_generated_sources(&model, &target)?;
    files_written += write_wit_and_lock("design", &target)?;
    make_build_sh_executable(&target)?;

    print_summary(&model, &target, files_written);
    Ok(())
}

fn build_context(model: &ConnectorModel, slug: &str) -> Context {
    let mut ctx = Context::new();
    let id = crate::commands::new::default_id(slug);
    ctx.set("name", slug.to_string());
    ctx.set("name_underscore", slug.replace('-', "_"));
    ctx.set("id", id.clone());
    ctx.set("id_wit", id_to_wit_package(&id));
    ctx.set(
        "version",
        if model.version.trim().is_empty() {
            "0.1.0".to_string()
        } else {
            model.version.clone()
        },
    );
    ctx.set("author", json_string_body(&detect_git_author()));
    ctx.set("license", "Apache-2.0");
    // `describe.json.tmpl` is JSON, and `model.name` is arbitrary text taken
    // from the spec's `info.title` (may contain quotes/backslashes) — the
    // `{{key}}` engine is a plain string replace, so every value destined for
    // a JSON string context must be pre-escaped for JSON here.
    ctx.set(
        "summary",
        json_string_body(&format!(
            "Generated by `gtdx openapi` from the {} spec.",
            model.name
        )),
    );
    ctx.set("runtime_ref_key", slug.to_string());
    ctx.set("sdk_version", env!("CARGO_PKG_VERSION"));
    // The designer floor is the describe-contract floor, not the generating
    // SDK version — see `compat::MIN_DESIGNER_VERSION`.
    ctx.set(
        "min_designer_version",
        greentic_extension_sdk_contract::compat::MIN_DESIGNER_VERSION,
    );
    // `extension-base`/`extension-host`/`extension-design` are versioned
    // independently (see `embedded::CONTRACT_VERSION`'s doc comment) —
    // `world.wit.tmpl` imports/exports each at its own real `@version`
    // rather than assuming they all match `CONTRACT_VERSION`, or
    // `cargo component` fails to resolve the scaffolded `wit/deps/` (the
    // package it finds on disk doesn't match the version the world asks
    // for).
    ctx.set(
        "base_version",
        embedded_package_version("extension-base.wit"),
    );
    ctx.set(
        "host_version",
        embedded_package_version("extension-host.wit"),
    );
    ctx.set(
        "design_version",
        embedded_package_version("extension-design.wit"),
    );
    ctx.set("network_json", network_allowlist_json(model));
    ctx.set("secrets_json", secrets_json(model));
    ctx.set("tools_contrib_json", tools_contrib_json(model, slug));
    ctx
}

/// Render every `templates/openapi-connector/*.tmpl` file (the static glue:
/// `Cargo.toml`, `describe.json`, `wit/world.wit`, `src/lib.rs`,
/// `rust-toolchain.toml`, `build.sh`) through the `{{key}}` engine.
fn render_static_templates(ctx: &Context, target: &Path) -> anyhow::Result<usize> {
    let mut files_written = 0usize;
    for entry in template::load_templates_kind("openapi-connector") {
        let dst = target.join(&entry.dst_rel);
        let rendered = ctx.render(std::str::from_utf8(entry.src_bytes)?)?;
        template::write_file(&dst, rendered.as_bytes())?;
        files_written += 1;
    }
    Ok(files_written)
}

/// Write the per-tool generated sources built in code by [`codegen`]
/// (`src/tool_meta.rs`, `src/dispatch.rs`) — these are NOT `{{key}}`
/// templates since their shape (one `TOOLS`/`REQUESTS` entry per tool) is
/// variable-length.
fn write_generated_sources(model: &ConnectorModel, target: &Path) -> anyhow::Result<usize> {
    template::write_file(
        &target.join("src/tool_meta.rs"),
        gen_tool_meta(model).as_bytes(),
    )?;
    template::write_file(
        &target.join("src/dispatch.rs"),
        gen_dispatch(model).as_bytes(),
    )?;
    Ok(2)
}

#[cfg(unix)]
fn make_build_sh_executable(target: &Path) -> anyhow::Result<()> {
    use std::os::unix::fs::PermissionsExt;
    let path = target.join("build.sh");
    if path.exists() {
        let mut perms = fs::metadata(&path)?.permissions();
        perms.set_mode(0o755);
        fs::set_permissions(&path, perms)?;
    }
    Ok(())
}

#[cfg(not(unix))]
fn make_build_sh_executable(_target: &Path) -> anyhow::Result<()> {
    Ok(())
}

fn print_summary(model: &ConnectorModel, target: &Path, files_written: usize) {
    println!();
    println!(
        "Generated \"{}\" connector at {} ({} files, {} tool(s)).",
        model.name,
        target.display(),
        files_written,
        model.tools.len()
    );
    println!();
    println!("Next steps:");
    println!("  cd {}", target.display());
    println!("  ./build.sh                          # cargo component build -> .gtxpack");
    println!(
        "  gtdx publish --wasm target/wasm32-wasip2/release/*.wasm --manifest Cargo.toml .   # or publish the .gtxpack directly"
    );
}

fn detect_git_author() -> String {
    std::process::Command::new("git")
        .args(["config", "--get", "user.name"])
        .output()
        .ok()
        .and_then(|o| {
            if o.status.success() {
                let s = String::from_utf8_lossy(&o.stdout).trim().to_string();
                if s.is_empty() { None } else { Some(s) }
            } else {
                None
            }
        })
        .unwrap_or_else(|| "Unknown".to_string())
}

/// Escape `s` for embedding inside an already-quoted JSON string context in a
/// `{{key}}` template (i.e. `"field": "{{key}}"`) — the returned text has no
/// surrounding quotes, just the escaped body.
fn json_string_body(s: &str) -> String {
    let quoted = serde_json::to_string(s).unwrap_or_default();
    quoted
        .strip_prefix('"')
        .and_then(|s| s.strip_suffix('"'))
        .unwrap_or(&quoted)
        .to_string()
}

/// The real `@version` an embedded WIT file (e.g. `extension-host.wit`)
/// declares on its `package greentic:<name>@X.Y.Z;` line — see
/// [`embedded::package_version`]. Panics if the named file isn't embedded or
/// declares no parseable version: both are scaffolding bugs, not user input
/// errors, and should fail loudly rather than silently emit a mismatched
/// `world.wit`.
fn embedded_package_version(file_name: &str) -> String {
    embedded::wit_files()
        .into_iter()
        .find(|f| f.name == file_name)
        .and_then(|f| embedded::package_version(f.bytes))
        .unwrap_or_else(|| panic!("embedded {file_name} missing or declares no @version"))
}

fn id_to_wit_package(id: &str) -> String {
    // com.example.demo -> com-example:demo
    let mut parts: Vec<&str> = id.split('.').collect();
    let last = parts.pop().unwrap_or("ext");
    format!("{}:{}", parts.join("-"), last)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture_spec_path() -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("src/commands/openapi/fixtures/petstore-min.json")
    }

    #[test]
    fn run_generates_a_full_design_extension_connector() {
        let tmp = tempfile::tempdir().unwrap();
        let out_dir = tmp.path().join("petstore-mini");
        let args = Args {
            spec: fixture_spec_path(),
            name: None,
            out: Some(out_dir.clone()),
            base_url: None,
        };

        run(&args).expect("run should succeed on the fixture spec");

        // describe.json: kind DesignExtension, network allow-list from
        // servers[], secret from the securityScheme.
        let describe: serde_json::Value =
            serde_json::from_slice(&fs::read(out_dir.join("describe.json")).unwrap()).unwrap();
        assert_eq!(describe["kind"], "DesignExtension");
        assert_eq!(
            describe["runtime"]["permissions"]["network"],
            serde_json::json!(["https://api.example.com/v1/*"])
        );
        assert_eq!(
            describe["runtime"]["permissions"]["secrets"],
            serde_json::json!(["secret://petstore-mini/bearerAuth"])
        );
        let tools = describe["contributions"]["tools"].as_array().unwrap();
        assert_eq!(tools.len(), 2);

        // Generated per-tool sources.
        let tool_meta = fs::read_to_string(out_dir.join("src/tool_meta.rs")).unwrap();
        assert!(tool_meta.contains("getPetById"));
        assert!(tool_meta.contains("createPet"));

        let dispatch = fs::read_to_string(out_dir.join("src/dispatch.rs")).unwrap();
        assert!(dispatch.contains("pub fn invoke"));

        // Static glue.
        assert!(out_dir.join("Cargo.toml").is_file());
        assert!(out_dir.join("src/lib.rs").is_file());
        assert!(out_dir.join("wit/world.wit").is_file());
        assert!(out_dir.join("rust-toolchain.toml").is_file());
        assert!(out_dir.join("build.sh").is_file());

        // WIT deps + contract lock (written by `write_wit_and_lock("design", ..)`).
        assert!(
            out_dir
                .join("wit/deps/greentic/extension-design/world.wit")
                .is_file()
        );
        assert!(out_dir.join(".gtdx-contract.lock").is_file());

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = fs::metadata(out_dir.join("build.sh"))
                .unwrap()
                .permissions()
                .mode();
            assert_eq!(mode & 0o111, 0o111, "build.sh must be executable");
        }
    }

    /// `run` defaults the output dir to `./<slug>` when `--out` is omitted.
    /// Exercised via the same slug helper `run` uses, rather than mutating
    /// the process-wide CWD (unsafe alongside other tests in this binary,
    /// which run multi-threaded in the same process).
    #[test]
    fn default_output_dir_is_the_slugified_connector_name() {
        let bytes = fs::read(fixture_spec_path()).unwrap();
        let model = parse_openapi(&bytes, None, None).unwrap();
        assert_eq!(slugify(&model.name), "petstore-mini");
    }
}
