#!/usr/bin/env bash
set -euo pipefail

# `src/bindings.rs` is generated by wit-bindgen and is gitignored, so a
# freshly cloned or scaffolded project doesn't have it on disk yet. Most kinds
# declare `mod bindings;` in `src/lib.rs`, which won't even resolve without
# the file — fmt, clippy, and test all fail on it before anything else.
# `cargo component bindings` regenerates just that file (no wasm build, no
# wit-bindgen invoked twice by the real build below): it's the fast,
# side-effect-free way to satisfy that prerequisite up front.
cargo component bindings

# `cargo fmt --all -- --check` walks the module tree from `src/lib.rs`. Where
# that pulls in generated `src/bindings.rs` (via `mod bindings;`), the mod
# declaration carries `#[rustfmt::skip]` — that file is never hand-formatted,
# it's regenerated on every build — so this check leaves it alone. Every
# author-written source file is still checked.
cargo fmt --all -- --check

cargo clippy --all-targets -- -D warnings
cargo test
./build.sh
